import { Game } from './types';

export const GAMES: Game[] = [
  // 25 Micro-games
  {
    id: '1',
    slug: 'emoji-charades',
    name: 'Emoji Charades',
    flag: 'EMOJI_CHARADES',
    status: 'active',
    category: 'puzzle',
    difficulty: 'easy',
    description: 'Guess the phrase from emoji clues!',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '2',
    slug: 'fast-math',
    name: 'Fast Math',
    flag: 'FAST_MATH',
    status: 'active',
    category: 'brain',
    difficulty: 'medium',
    description: 'Quick mental math challenges',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '3',
    slug: 'word-snap',
    name: 'Word Snap',
    flag: 'WORD_SNAP',
    status: 'active',
    category: 'word',
    difficulty: 'easy',
    description: 'Find words as fast as you can!',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '4',
    slug: 'color-match',
    name: 'Color Match',
    flag: 'COLOR_MATCH',
    status: 'active',
    category: 'visual',
    difficulty: 'easy',
    description: 'Match colors before time runs out',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '5',
    slug: 'memory-flip',
    name: 'Memory Flip',
    flag: 'MEMORY_FLIP',
    status: 'active',
    category: 'memory',
    difficulty: 'medium',
    description: 'Classic memory card matching game',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '6',
    slug: 'pixel-zoom',
    name: 'Pixel Zoom',
    flag: 'PIXEL_ZOOM',
    status: 'active',
    category: 'visual',
    difficulty: 'hard',
    description: 'Guess the image from zoomed pixels',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '7',
    slug: 'geo-quick',
    name: 'Geo Quick',
    flag: 'GEO_QUICK',
    status: 'active',
    category: 'knowledge',
    difficulty: 'medium',
    description: 'Quick geography challenges',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '8',
    slug: 'reaction-test',
    name: 'Reaction Test',
    flag: 'REACTION_TEST',
    status: 'active',
    category: 'reflex',
    difficulty: 'easy',
    description: 'Test your reaction speed',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '9',
    slug: 'sound-bite',
    name: 'Sound Bite Guess',
    flag: 'SOUND_BITE_GUESS',
    status: 'active',
    category: 'audio',
    difficulty: 'medium',
    description: 'Identify sounds and music clips',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '10',
    slug: 'finish-quote',
    name: 'Finish the Quote',
    flag: 'FINISH_QUOTE',
    status: 'active',
    category: 'knowledge',
    difficulty: 'medium',
    description: 'Complete famous quotes',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '11',
    slug: 'tap-race',
    name: 'Tap Race',
    flag: 'TAP_RACE',
    status: 'active',
    category: 'reflex',
    difficulty: 'easy',
    description: 'Tap as fast as you can!',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '12',
    slug: 'emoji-bingo',
    name: 'Emoji Bingo',
    flag: 'EMOJI_BINGO',
    status: 'active',
    category: 'puzzle',
    difficulty: 'easy',
    description: 'Bingo with emoji patterns',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '13',
    slug: 'riddle',
    name: 'Daily Riddle',
    flag: 'DAILY_RIDDLE',
    status: 'active',
    category: 'puzzle',
    difficulty: 'hard',
    description: 'Solve challenging riddles',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '14',
    slug: 'micro-crossword',
    name: 'Micro Crossword',
    flag: 'MICRO_CROSSWORD',
    status: 'active',
    category: 'word',
    difficulty: 'medium',
    description: 'Mini crossword puzzles',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '15',
    slug: 'scramble-caption',
    name: 'Scramble Caption',
    flag: 'SCRAMBLE_CAPTION',
    status: 'active',
    category: 'word',
    difficulty: 'medium',
    description: 'Unscramble image captions',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '16',
    slug: 'sticker-toss',
    name: 'Sticker Toss',
    flag: 'STICKER_TOSS',
    status: 'active',
    category: 'arcade',
    difficulty: 'easy',
    description: 'Toss stickers to hit targets',
    isPremium: false,
    createdAt: new Date()
  },
  // Existing carryover games
  {
    id: '17',
    slug: 'one-click-tag',
    name: 'One Click Tag',
    flag: 'ONE_CLICK_TAG',
    status: 'active',
    category: 'social',
    difficulty: 'easy',
    description: 'Tag friends with one click',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '18',
    slug: 'post-a-pic',
    name: 'Post a Pic',
    flag: 'POST_A_PIC',
    status: 'active',
    category: 'social',
    difficulty: 'easy',
    description: 'Share and rate pictures',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '19',
    slug: 'caption-this',
    name: 'Caption This',
    flag: 'CAPTION_THIS',
    status: 'active',
    category: 'creative',
    difficulty: 'easy',
    description: 'Write funny captions',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '20',
    slug: 'quick-poll-duel',
    name: 'Quick Poll Duel',
    flag: 'QUICK_POLL_DUEL',
    status: 'active',
    category: 'social',
    difficulty: 'easy',
    description: 'Battle with quick polls',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '21',
    slug: 'two-truths',
    name: 'Two Truths',
    flag: 'TWO_TRUTHS',
    status: 'active',
    category: 'social',
    difficulty: 'medium',
    description: 'Two truths and a lie game',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '22',
    slug: 'trivia-blitz',
    name: 'Trivia Blitz',
    flag: 'TRIVIA_BLITZ',
    status: 'active',
    category: 'knowledge',
    difficulty: 'medium',
    description: 'Fast-paced trivia questions',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '23',
    slug: 'would-you-rather',
    name: 'Would You Rather',
    flag: 'WOULD_YOU_RATHER',
    status: 'active',
    category: 'social',
    difficulty: 'easy',
    description: 'Choose between tough options',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '24',
    slug: 'rps',
    name: 'Rock Paper Scissors',
    flag: 'RPS',
    status: 'active',
    category: 'classic',
    difficulty: 'easy',
    description: 'Classic rock paper scissors',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '25',
    slug: 'reaction-streaks',
    name: 'Reaction Streaks',
    flag: 'REACTION_STREAKS',
    status: 'active',
    category: 'reflex',
    difficulty: 'hard',
    description: 'Build reaction streaks',
    isPremium: true,
    createdAt: new Date()
  },
  // 50 Challenging Add-On Games
  {
    id: '26',
    slug: 'cryptic-cross',
    name: 'Cryptic Cross Mini',
    flag: 'CRYPTIC_CROSS',
    status: 'active',
    category: 'word',
    difficulty: 'hard',
    description: 'Solve cryptic crossword clues',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '27',
    slug: 'word-ladder',
    name: 'Word Ladder Rush',
    flag: 'WORD_LADDER',
    status: 'active',
    category: 'word',
    difficulty: 'medium',
    description: 'Transform words one letter at a time',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '28',
    slug: 'anagram-gauntlet',
    name: 'Master Anagram Gauntlet',
    flag: 'ANAGRAM_GAUNTLET',
    status: 'active',
    category: 'word',
    difficulty: 'hard',
    description: 'Extreme anagram challenges',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '29',
    slug: 'definition-duel',
    name: 'Definition Duel',
    flag: 'DEFINITION_DUEL',
    status: 'active',
    category: 'word',
    difficulty: 'medium',
    description: 'Match words to definitions',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '30',
    slug: 'quote-cipher',
    name: 'Quote Cipher',
    flag: 'QUOTE_CIPHER',
    status: 'active',
    category: 'word',
    difficulty: 'hard',
    description: 'Decode encrypted quotes',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '31',
    slug: 'wiki-trail',
    name: 'Wiki Trail',
    flag: 'WIKI_TRAIL',
    status: 'active',
    category: 'knowledge',
    difficulty: 'medium',
    description: 'Navigate Wikipedia connections',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '32',
    slug: 'geo-typo',
    name: 'Geo Typo Hunt',
    flag: 'GEO_TYPO',
    status: 'active',
    category: 'knowledge',
    difficulty: 'medium',
    description: 'Find geography typos',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '33',
    slug: 'flag-forge',
    name: 'Flag Forge',
    flag: 'FLAG_FORGE',
    status: 'active',
    category: 'knowledge',
    difficulty: 'medium',
    description: 'Identify world flags',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '34',
    slug: 'formula-fix',
    name: 'Formula Fix',
    flag: 'FORMULA_FIX',
    status: 'active',
    category: 'puzzle',
    difficulty: 'hard',
    description: 'Repair broken formulas',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '35',
    slug: 'rogue-riddle',
    name: 'Rogue Riddle',
    flag: 'ROGUE_RIDDLE',
    status: 'active',
    category: 'puzzle',
    difficulty: 'hard',
    description: 'Procedurally generated riddles',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '36',
    slug: 'killer-sudoku',
    name: 'Killer Sudoku Mini',
    flag: 'KILLER_SUDOKU',
    status: 'active',
    category: 'puzzle',
    difficulty: 'hard',
    description: 'Sudoku with sum cages',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '37',
    slug: 'nonogram',
    name: 'Nonogram Vault',
    flag: 'NONOGRAM_VAULT',
    status: 'active',
    category: 'puzzle',
    difficulty: 'medium',
    description: 'Picture logic puzzles',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '38',
    slug: 'kakuro',
    name: 'Kakuro Sprint',
    flag: 'KAKURO_SPRINT',
    status: 'active',
    category: 'puzzle',
    difficulty: 'hard',
    description: 'Mathematical crossword',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '39',
    slug: 'lights-out',
    name: 'Lights Out Labs',
    flag: 'LIGHTS_OUT',
    status: 'active',
    category: 'puzzle',
    difficulty: 'medium',
    description: 'Toggle lights puzzle',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '40',
    slug: 'river-crossing',
    name: 'River Crossing+',
    flag: 'RIVER_CROSSING',
    status: 'active',
    category: 'puzzle',
    difficulty: 'hard',
    description: 'Logic transport puzzle',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '41',
    slug: 'circuit-trace',
    name: 'Circuit Trace',
    flag: 'CIRCUIT_TRACE',
    status: 'active',
    category: 'puzzle',
    difficulty: 'hard',
    description: 'Complete electrical circuits',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '42',
    slug: 'tetrio-logic',
    name: 'Tetrio Logic',
    flag: 'TETRIO_LOGIC',
    status: 'active',
    category: 'puzzle',
    difficulty: 'hard',
    description: 'Tetromino logic puzzles',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '43',
    slug: 'rush-hour',
    name: 'Rush Hour Remix',
    flag: 'RUSH_HOUR_REMIX',
    status: 'active',
    category: 'puzzle',
    difficulty: 'medium',
    description: 'Sliding block puzzle',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '44',
    slug: 'island-count',
    name: 'Island Count',
    flag: 'ISLAND_COUNT',
    status: 'active',
    category: 'puzzle',
    difficulty: 'medium',
    description: 'Count connected islands',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '45',
    slug: 'pathfinder',
    name: 'Pathfinder Maze',
    flag: 'PATHFINDER_MAZE',
    status: 'active',
    category: 'puzzle',
    difficulty: 'hard',
    description: 'Optimal path finding',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '46',
    slug: 'vector-drift',
    name: 'Vector Drift',
    flag: 'VECTOR_DRIFT',
    status: 'active',
    category: 'arcade',
    difficulty: 'hard',
    description: 'Physics-based drifting',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '47',
    slug: 'grapple-run',
    name: 'Grapple Run',
    flag: 'GRAPPLE_RUN',
    status: 'active',
    category: 'arcade',
    difficulty: 'hard',
    description: 'Grappling hook platformer',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '48',
    slug: 'bullet-weave',
    name: 'Bullet Weave',
    flag: 'BULLET_WEAVE',
    status: 'active',
    category: 'arcade',
    difficulty: 'hard',
    description: 'Dodge bullet patterns',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '49',
    slug: 'portal-putter',
    name: 'Portal Putter',
    flag: 'PORTAL_PUTTER',
    status: 'active',
    category: 'arcade',
    difficulty: 'medium',
    description: 'Golf with portals',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '50',
    slug: 'time-splitter',
    name: 'Time Splitter',
    flag: 'TIME_SPLITTER',
    status: 'active',
    category: 'arcade',
    difficulty: 'hard',
    description: 'Time manipulation puzzler',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '51',
    slug: 'mirror-dash',
    name: 'Mirror Dash',
    flag: 'MIRROR_DASH',
    status: 'active',
    category: 'arcade',
    difficulty: 'hard',
    description: 'Mirrored controls challenge',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '52',
    slug: 'orbital-catch',
    name: 'Orbital Catch',
    flag: 'ORBITAL_CATCH',
    status: 'active',
    category: 'arcade',
    difficulty: 'medium',
    description: 'Orbital mechanics game',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '53',
    slug: 'rhythm-reactor',
    name: 'Rhythm Reactor',
    flag: 'RHYTHM_REACTOR',
    status: 'active',
    category: 'arcade',
    difficulty: 'medium',
    description: 'Rhythm-based reactor',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '54',
    slug: 'stacksmith',
    name: 'Stacksmith',
    flag: 'STACKSMITH',
    status: 'active',
    category: 'arcade',
    difficulty: 'medium',
    description: 'Precision stacking',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '55',
    slug: 'vector-sniper',
    name: 'Vector Sniper',
    flag: 'VECTOR_SNIPER',
    status: 'active',
    category: 'arcade',
    difficulty: 'hard',
    description: 'Precision vector aiming',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '56',
    slug: 'tower-forge',
    name: 'Mini Tower Forge',
    flag: 'TOWER_FORGE',
    status: 'active',
    category: 'arcade',
    difficulty: 'medium',
    description: 'Quick tower defense',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '57',
    slug: 'deck-duel',
    name: 'Deck Duel Micro',
    flag: 'DECK_DUEL',
    status: 'active',
    category: 'arcade',
    difficulty: 'medium',
    description: 'Fast card battles',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '58',
    slug: 'hex-conquest',
    name: 'Hex Conquest',
    flag: 'HEX_CONQUEST',
    status: 'active',
    category: 'arcade',
    difficulty: 'hard',
    description: 'Hex grid strategy',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '59',
    slug: 'relic-run',
    name: 'Relic Run',
    flag: 'RELIC_RUN',
    status: 'active',
    category: 'arcade',
    difficulty: 'medium',
    description: 'Collect ancient relics',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '60',
    slug: 'factory-flow',
    name: 'Factory Flow',
    flag: 'FACTORY_FLOW',
    status: 'active',
    category: 'arcade',
    difficulty: 'medium',
    description: 'Optimize factory lines',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '61',
    slug: 'nano-colony',
    name: 'Nano Colony',
    flag: 'NANO_COLONY',
    status: 'active',
    category: 'arcade',
    difficulty: 'hard',
    description: 'Micro civilization sim',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '62',
    slug: 'crypt-raider',
    name: 'Crypt Raider',
    flag: 'CRYPT_RAIDER',
    status: 'active',
    category: 'arcade',
    difficulty: 'hard',
    description: 'Dungeon exploration',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '63',
    slug: 'signal-jam',
    name: 'Signal Jam',
    flag: 'SIGNAL_JAM',
    status: 'active',
    category: 'arcade',
    difficulty: 'medium',
    description: 'Wave signal matching',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '64',
    slug: 'blitz-draw',
    name: 'Blitz Draw',
    flag: 'BLITZ_DRAW',
    status: 'active',
    category: 'social',
    difficulty: 'easy',
    description: 'Speed drawing game',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '65',
    slug: 'trivia-arena',
    name: 'Trivia Arena Live',
    flag: 'TRIVIA_ARENA',
    status: 'active',
    category: 'knowledge',
    difficulty: 'medium',
    description: 'Live trivia battles',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '66',
    slug: 'word-snipe',
    name: 'Word Snipe',
    flag: 'WORD_SNIPE',
    status: 'active',
    category: 'word',
    difficulty: 'hard',
    description: 'Competitive word finding',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '67',
    slug: 'tap-dueler',
    name: 'Tap Dueler',
    flag: 'TAP_DUELER',
    status: 'active',
    category: 'reflex',
    difficulty: 'medium',
    description: 'Head-to-head tapping',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '68',
    slug: 'emoji-heist',
    name: 'Emoji Heist',
    flag: 'EMOJI_HEIST',
    status: 'active',
    category: 'puzzle',
    difficulty: 'medium',
    description: 'Plan the perfect heist',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '69',
    slug: 'bluff-tell',
    name: 'Bluff & Tell',
    flag: 'BLUFF_TELL',
    status: 'active',
    category: 'social',
    difficulty: 'medium',
    description: 'Deception and truth',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '70',
    slug: 'sound-match',
    name: 'Sound Match Pro',
    flag: 'SOUND_MATCH_PRO',
    status: 'active',
    category: 'audio',
    difficulty: 'hard',
    description: 'Advanced audio matching',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '71',
    slug: 'palette-pilot',
    name: 'Palette Pilot',
    flag: 'PALETTE_PILOT',
    status: 'active',
    category: 'visual',
    difficulty: 'medium',
    description: 'Color palette navigation',
    isPremium: false,
    createdAt: new Date()
  },
  {
    id: '72',
    slug: 'zoom-id',
    name: 'Zoom ID Expert',
    flag: 'ZOOM_ID_EXPERT',
    status: 'active',
    category: 'visual',
    difficulty: 'hard',
    description: 'Expert zoom identification',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '73',
    slug: 'pattern-prophet',
    name: 'Pattern Prophet',
    flag: 'PATTERN_PROPHET',
    status: 'active',
    category: 'puzzle',
    difficulty: 'hard',
    description: 'Predict pattern sequences',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '74',
    slug: 'memory-labyrinth',
    name: 'Memory Labyrinth',
    flag: 'MEMORY_LABYRINTH',
    status: 'active',
    category: 'memory',
    difficulty: 'hard',
    description: 'Navigate from memory',
    isPremium: true,
    createdAt: new Date()
  },
  {
    id: '75',
    slug: 'reflex-gauntlet',
    name: 'Reflex Gauntlet',
    flag: 'REFLEX_GAUNTLET',
    status: 'active',
    category: 'reflex',
    difficulty: 'hard',
    description: 'Ultimate reflex challenge',
    isPremium: true,
    createdAt: new Date()
  }
];

export const EXTREME_GAME: Game = {
  id: 'extreme-1',
  slug: 'ascension',
  name: 'Ascension',
  flag: 'EXTREME_ASCENSION',
  status: 'active',
  category: 'extreme',
  difficulty: 'hard',
  description: 'Season-based extreme challenge game',
  isPremium: true,
  createdAt: new Date()
};

export function getGameBySlug(slug: string): Game | undefined {
  return [...GAMES, EXTREME_GAME].find(game => game.slug === slug);
}

export function getGamesByCategory(category: string): Game[] {
  return GAMES.filter(game => game.category === category);
}

export function getFreeGames(): Game[] {
  return GAMES.filter(game => !game.isPremium);
}

export function getPremiumGames(): Game[] {
  return GAMES.filter(game => game.isPremium);
}